server:
  port: 8060
spring:
  application:
    name: NewsServer
  datasource:
    url: jdbc:mysql://localhost:3306/lala_news?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   # 时间显示格式
    time-zone: GMT+8
#    default-property-inclusion: non_null  #返回null值不显示
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #驼峰转化

eureka:
  instance:
    prefer-ip-address: true   #显示主机id
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/