server:
  port: 8090
spring:
  application:
    name: SearchServer
  datasource:
    url: jdbc:mysql://localhost:3306/lala_news?serverTimezone=UTC
    #    部署微服务后的地址
    # url: jdbc:mysql://mysql:3306/lala_news?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   # 时间显示格式
    time-zone: GMT+8
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #驼峰转化
eureka:
  instance:
    prefer-ip-address: true   #显示主机id
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      上线地址  通过docker容器名eureka-server进行访问
#      defaultZone: http://eureka-server:8761/eureka/